service: quadrivia

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  memorySize: 128

plugins:
  - serverless-plugin-typescript

functions:
  onHealthCheck:
    handler: src/index.onHealthCheckHandler
    events:
      - http:
          path: /
          method: ANY
          cors: true
